#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

case `uname` in
  Darwin)
    export PATH="$HOME/.conf/bin:$PATH"
    alias ls="ls -G"
    alias lsblk="diskutil list"
    ;;
  Linux)
    alias ls='ls --color=auto'
    ;;
esac


PS1='[\u@\h \W]\$ '
