if has("gui_macvim")
  set guifont=Monaco:h12
elseif has("gui_win32")
  set guifont=Consolas:h12
  set antialias
  set backspace=indent,eol,start
  set guioptions-=m  "remove menu bar
  set guioptions-=T  "remove toolbar
  set guioptions-=r  "remove right-hand scroll bar
  set guioptions-=L  "remove left-hand scroll bar
elseif has("gui_gtk2")
  set guifont=Ubuntu\ Mono\ 12
endif
