#!/usr/bin/env ruby
here = File.expand_path File.dirname __FILE__
case RbConfig::CONFIG['host_os']
when /darwin|mac os/
  Process.wait Process.spawn({
    "MAC_MANIFEST" => File.join(here, "osx.rb"),
    "MY_DOTFILES" => File.join(here, "dotfiles"),
    "MY_BINS" => File.join(here, "bin")
  }, "/bin/zsh", "-c", "ruby $MAC_MANIFEST")
end
