#!/bin/bash

function manifest() {
  pushd $DOTCONF > /dev/null
  git remote set-url origin git@github.com:keyvanfatehi/.conf.git
  popd > /dev/null
  MY_DOTFILES=$DOTCONF/dotfiles
  MY_BINS=$DOTCONF/bin
  MY_NODE_BINS=$DOTCONF/node_modules/.bin
  source $DOTCONF/$1.sh
}

case `uname` in
  Linux)
    DOTCONF=$(dirname $(readlink -f $0))
    manifest "deb"
    ;;
  Darwin)
    # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
    TARGET_FILE=$0

    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`

    # Iterate down a (possible) chain of symlinks
    while [ -L "$TARGET_FILE" ]
    do
      TARGET_FILE=`readlink $TARGET_FILE`
      cd `dirname $TARGET_FILE`
      TARGET_FILE=`basename $TARGET_FILE`
    done

    # Compute the canonicalized name by finding the physical path 
    # for the directory we're in and appending the target file.
    PHYS_DIR=`pwd -P`
    RESULT=$PHYS_DIR/$TARGET_FILE
    DOTCONF=$(dirname $RESULT)
    manifest "osx"
    ;;
esac
