#!/bin/bash

DeterminePlatform() {
  PLATFORM="unknown"
  case `uname` in
    Linux)
      if [ -f /etc/arch-release ] ; then
        PLATFORM="archlinux"
      elif [ -f /etc/lsb-release ]; then
        PLATFORM="ubuntu"
      fi
      ;;
    Darwin)
      PLATFORM="darwin"
      ;;
  esac
  if [ "$PLATFORM" = "unknown" ]; then
    echo "failed to determine platform"
    return -1
  else
    echo "you are on $PLATFORM"
  fi
}

UpdatePackageManagers() {
  case $PLATFORM in 
    archlinux)
      echo "Invoking pacman to synchronize package list"
      sudo pacman -Sy
      return $?
      ;;
    ubuntu)
      echo "Updating apt packages ..."
      DEBIAN_FRONTEND=noninteractive sudo apt-get update
      return $?
      ;;
    darwin)
      if hash brew > /dev/null 2>&1; then
        echo "Updating brew packages ..."
        brew update
      else
        echo "Installing brew"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      fi
      return $?
      ;;
  esac
}

RequirePackage() {
  hash $1 >/dev/null 2>&1 || {
    case $PLATFORM in 
      archlinux)
        sudo pacman -S $1
        return $?
        ;;
      ubuntu)
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y $1
        return $?
        ;;
      darwin)
        brew install -y $1
        return $?
        ;;
    esac
  }
}

GetRequirements() {
  RequirePackage "git" && test -d $HOME/.conf || git clone https://github.com/kfatehi/.conf $HOME/.conf
}

DeterminePlatform && UpdatePackageManagers && GetRequirements && echo $'  Ready! Run this:\n\tbash .conf/bootstrap'
