# load X settings
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# keyboard repeat rate
xset r rate 200 25

# wallpaper
feh --bg-fill --no-fehbg /usr/local/share/backgrounds/think_correctly.png

# hide mouse after 4 sec
unclutter -idle 4 &

# setup dwm status bar
while xsetroot -name "$($HOME/.dwm-status)"
do
  sleep 1
done &

# start dwm
exec dwm > $HOME/.dwm.log 2>&1
